# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHON_VERSION=3.10 \
    ANSIBLE_VERSION=2.15.13
#   PATH=/home/devops/.local/bin:$PATH

# Install necessary tools and libraries
RUN apt-get update && apt-get install -y \
    software-properties-common \
    sudo \
    python3.10 \
    python3.10-venv \
    python3.10-dev \
    python3-pip \
    gcc \
    make \
    git \
    openssh-client \
    openssh-server \
    curl \
    gnupg \
    libyaml-dev \
    vim \
    sshpass \
    && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 \
    && pip3 install --no-cache-dir "ansible-core==${ANSIBLE_VERSION}" jinja2==3.1.2 paramiko \
    && ansible-galaxy collection install community.general \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user "devops" with fixed UID and GID
# RUN groupadd -g 2222 devops && \
#     useradd -u 2222 -g 2222 -m -s /bin/bash devops && \
#     echo 'devops ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
#     mkdir -p /home/devops/.ssh && \
#     mkdir -p /home/devops/ansible-projects && \
#     chown -R devops:devops /home/devops

# Update SSH configuration
# RUN echo 'AllowUsers devops' >> /etc/ssh/sshd_config && \
#     sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config && \
#     sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config

# Set the working directory
# WORKDIR /home/devops/ansible-projects
# WORKDIR /ansible-projects
WORKDIR /ansible

# Switch to the "devops" user 
# USER devops

# Set the default command
CMD ["/bin/bash"]
