---
- name: Check OS information
  hosts: TestLab
  become: true
  vars:
    csv_path: /ansible/reports
    csv_filename: report.csv
    headers: IP,check_ip_version_kernel,check_timezone,check_var_partition_conf,check_app_partition_conf
  tasks:
  - name: Create CSV headers
    ansible.builtin.lineinfile:
      dest: "{{ csv_path }}/{{ csv_filename }}"
      line: "{{ headers }}"
      create: true
      state: present
    delegate_to: localhost
    run_once: true

  - name: Execute all roles and save the results to CSV file....
    include_role:
      name: "{{ item }}"
    loop:
      - check_ip_version_kernel
      - check_timezone
      - check_var_partition_conf
      - check_app_partition_conf

  - name: Build out CSV file
    ansible.builtin.lineinfile:
      dest: "{{ csv_path }}/{{ csv_filename }}"
      line: "{{ inventory_hostname }},{{ check_ip_version_kernel }},{{ check_timezone }},{{ check_var_partition_conf }},{{ check_app_partition_conf }}"
      create: true
      state: present
    delegate_to: localhost